# Generated by Django 4.2.5 on 2023-09-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FuelPrice',
        ),
    ]
